version: 2.1
jobs:
  install:
    working_directory: /tmp
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run:
          name: install
          command: npm install
      - persist_to_workspace:
          root: /tmp
          paths: node_modules
  lint:
    working_directory: /tmp
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run:
          name: lint
          command: npm run lint
  build:
    working_directory: /tmp
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run:
          name: build lib
          command: npm run build
      - persist_to_workspace:
          root: /tmp
          paths: lib
  test:
    working_directory: /tmp
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run:
          name: test
          command: npm run test
  release:
    working_directory: /tmp
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run:
          name: semantic-release
          command: npm run semantic-release || true
workflows:
  version: 2

  btd:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - install
      - test:
          requires:
            - build
      - release:
          requires:
            - test